management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
