server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

springdoc:
    swagger-ui:
        use-root-path: true
        urls:
            - name: USER-SERVICE
              url: /user-service/v3/api-docs
            - name: INVENTORY-SERVICE
              url: /inventory-service/v3/api-docs
            - name: ORDER-SERVICE
              url: /order-service/v3/api-docs
            - name: PAYMENT-SERVICE
              url: /payment-service/v3/api-docs
    api-docs:
        enabled: true
        path: /v3/api-docs
